export const Questions = [
    {
        prompt: "What is the capital of France?",
        optionA: "Berlin",
        optionB: "Madrid",
        optionC: "Paris",
        optionD: "Rome",
        answer: "C",
    },
    {
        prompt: "Which planet is known as the Red Planet?",
        optionA: "Earth",
        optionB: "Mars",
        optionC: "Jupiter",
        optionD: "Saturn",
        answer: "B",
    },
    {
        prompt: "Who wrote 'Hamlet'?",
        optionA: "Mark Twain",
        optionB: "Charles Dickens",
        optionC: "Jane Austen",
        optionD: "William Shakespeare",
        answer: "D",
    },
    {
        prompt: "What is the largest ocean on Earth?",
        optionA: "Atlantic",
        optionB: "Indian",
        optionC: "Pacific",
        optionD: "Arctic",
        answer: "C",
    },
    {
        prompt: "Which element has the chemical symbol 'O'?",
        optionA: "Oxygen",
        optionB: "Gold",
        optionC: "Hydrogen",
        optionD: "Iron",
        answer: "A",
    },
    {
        prompt: "Who painted the Mona Lisa?",
        optionA: "Pablo Picasso",
        optionB: "Leonardo da Vinci",
        optionC: "Claude Monet",
        optionD: "Vincent van Gogh",
        answer: "B",
    },
    {
        prompt: "What is the smallest prime number?",
        optionA: "1",
        optionB: "2",
        optionC: "3",
        optionD: "5",
        answer: "B",
    },
    {
        prompt: "What is the boiling point of water at sea level?",
        optionA: "90°C",
        optionB: "100°C",
        optionC: "110°C",
        optionD: "120°C",
        answer: "B",
    },
    {
        prompt: "What is the largest mammal in the world?",
        optionA: "Elephant",
        optionB: "Blue Whale",
        optionC: "Great White Shark",
        optionD: "Giraffe",
        answer: "B",
    },
    {
        prompt: "Who discovered penicillin?",
        optionA: "Alexander Fleming",
        optionB: "Marie Curie",
        optionC: "Louis Pasteur",
        optionD: "Isaac Newton",
        answer: "A",
    },
];
